### PR TITLE
Fix overrideMap generation logic

### LINKED ISSUE #61: overrideMap generation can create cycles
I'm using these sweet utility functions & have noticed something that y'all might want to know about.

The process that creates an overrideMap & traverse nodes (to ensure block boundaries are detected) is nifty, but I've see it result in circular references resulting in an infinite loop.

Here you can see an example where the map contains a cycle:
image

What I have done is simply delete the entry for the current node in [forwardTraverse](https://github.com/GoogleChromeLabs/text-fragments-polyfill/blob/f0159ae64cc800d04fdbee6499f569a94ccf4915/src/fragment-generation-utils.js#L1017) once we map to it's parent resulting in progression past it's parent the second time around.
image
I'm not positive this results in the exact intended behavior, but it seems to be working well enough for me.

You can see for yourself at [this link](https://www.notboring.co/p/transforming-tata-0b9) with this selection:

image

The [chrome extension](https://chrome.google.com/webstore/detail/link-to-text-fragment/pbcodcjpfjdpcineamnnmbkkmkdpajjg?hl=en) craps out for this selection, but with my change it manges to create a valid TextFragment.
image

If my diff doesn't break any other assumptions I'd be happy to submit a PR.

### PR DESCRIPTION
**Pull request by guillaumejenkins**
The current |createForwardOverrideMap| function can create cycles, which could potentially lead to infinite loops when traversing the DOM under certain circumstances.

The problem is that when creating an override, |walker.nextNode()| is used to determine which node to traverse next. This is wrong if the node to be traversed next had already been overridden. The fix is to simply check the override map to see if the current node already had an override for its next node, and if so, use that as the ancestor's override.

Fixes #61

### CODE REVIEW

File: src/fragment-generation-utils.js [hunk 1]
```diff
@@ -989,13 +989,17 @@ const createForwardOverrideMap = (walker) => {
...
+
+    // Set a mapping from the found child to its ancestor.
     if (walker.currentNode !== node) overrideMap.set(walker.currentNode, node);
 
-    // Next, set a mapping from the ancestor to the node it displaced in the
-    // ordering. This might get overwritten later if another ancestor needs to
-    // get inserted in the ordering too.
-    overrideMap.set(node, walker.nextNode());
+    // Also set a mapping from the ancestor to the child's next node, which is
+    // |TreeWalker.nextNode()| unless it had already been overriden in the map.
```
Comment (tomayac) [inline src/fragment-generation-utils.js:999]:
```suggestion
    // |TreeWalker.nextNode()| unless it had already been overridden in the map.
```

Nit comment, I know…

File: src/fragment-generation-utils.js [hunk 2]
```diff
@@ -989,13 +989,17 @@ const createForwardOverrideMap = (walker) => {
...
+    // This might get overwritten later if another ancestor needs to get
```
Comment (tomayac) [inline src/fragment-generation-utils.js:1000]: Just to be sure: over_written_ or over_ridden_?

**Review by tomayac — CHANGES_REQUESTED** [review]
Thanks for the detective work! Just two small comments to address and then we're good to go.

File: src/fragment-generation-utils.js (hunk 1 above)
Comment (guillaumejenkins) [reply src/fragment-generation-utils.js:999]: Woops, ty!

File: src/fragment-generation-utils.js (hunk 2 above)
Comment (guillaumejenkins) [reply src/fragment-generation-utils.js:1000]: over_written_, i.e. the override will get changed to something else. I changed the wording, hopefully it's clearer now

**Review by tomayac — APPROVED** [review]
LGTM
